### ISSUE TITLE
Lighter .xconfig files

### ISSUE THREAD

**Issue by rei-vilo** [timknapen/Arduino-With-XCode#11]
All the parameters for the boards are in the boards.txt file.

So no need to copy/paste them into the .xconfig files.
- Uno.xconfig is now a single line file:
  `boardname = uno`
- Please find the corresponding function to add to the makefile:

```
BOARDS_TXT = /Applications/Mpide.app/Contents/Resources/Java/hardware/arduino/boards.txt

# result = $(call READ_BOARD_TXT, 'boardname.parameter', 'pathfileboards.txt')
nullstring  :=
spacestring := $(nullstring) # end of the line
equalstring := $(nullstring)=# end of the line
READ_BOARD_TXT = $(lastword $(subst $(equalstring),$(spacestring),$(shell grep -e$(1) $(2)))) 

boardname = uno
parameter = build.f_cpu
BF_CPU = $(call READ_BOARD_TXT, $(boardname).$(parameter), $(BOARDS_TXT))
```

**Comment by timknapen** [comment]
That looks great!! 
Do we still need the Xconfig files with this magic?
We can just add a build setting called "boardname", right? That would allow us to drop ALL the xconfig files!!

good job!!

**Comment by rei-vilo** [comment]
> Do we still need the Xconfig files with this magic?

IMHO, I think so, because it's clean. 

On top of that, users could tailor the name of their boards or add specific boards, provided they define the right identifier.

For example, I have an Arduino UNO board running at 14,7 MHz called Arduino Uno (14,7 MHz) with the specific identifier pro147.

**Comment by timknapen** [comment]
So you would make still the whole list of xconfig files, but they all have one line in them, defining the board name?
How would you switch between a board that is in the boards.txt file and one that is a user specific board (like your pro147) ?

**Comment by rei-vilo** [comment]
> So you would make still the whole list of xconfig files, but they all have one line in them, defining the board name?

Yes, because I've chipKIT in mind! 

So I want to address both platforms.

> How would you switch between a board that is in the boards.txt file and one that is a user specific board (like your pro147) ?

I've altered the boards.txt file and entered the specs manually.

**Comment by timknapen** [comment]
hmm, but if you alter the boards.txt file, we can just drop the whole list of xconfig files and set the boardname as a build setting, can't we? 

I see from your example that the chipkit IDE also has a boards.txt file, so there's really no need for the xconfig files anymore and you can still change to one of your custom boards because you've defined it in the boards.txt

I'm going to experiment with that makefile that you wrote.. it looks superduper!

**Comment by rei-vilo** [comment]
The Xcode 4.2 doesn't seem to have been updated on release **prettier output, better extracting variables from boards** dated Jan 23, 2012

**Comment by timknapen** [comment]
I know, I was working on my Snow Leopard computer at work and checking it out on mr. Lion Machine right now!

**Comment by rei-vilo** [comment]
> Snow Leopard at work, Lion at home

Dangerous animals, aren't they?

**Comment by timknapen** [comment]
The Lion behaved very well today :-)

**Comment by rei-vilo** [comment]
Great!
